### ISSUE TITLE
sync-rss手动运行失败

### ISSUE THREAD

**Issue by codyb1ue** [bambooom/douban-backup#106]
你好，按照博文设置好以后，手动测试了一下，但是没有跑通。

显示是这样的
Failed to handle the following feeds:
undefined: http://movie.douban.com/subject/34882958/
undefined: http://movie.douban.com/subject/1300678/
undefined: http://movie.douban.com/subject/6524236/
undefined: http://movie.douban.com/subject/27075556/
undefined: http://movie.douban.com/subject/36247982/
Error: Process completed with exit code 1.

另外，我在notion没有套用你的template模版，直接使用导出的csv，不知道是不是这个影响了添加新条目。

辛苦你抽空帮忙看看怎么回事，谢谢。

https://github.com/codyb1ue/douban-backup

**Comment by codyb1ue** [comment]
前面还会出现这种错误，warn: request fail { code: 'validation_error', message: '个人评分 is expected to be number.' }
Failed to create 没事偷着乐(http://movie.douban.com/subject/1300678/) with error:  APIResponseError: 个人评分 is expected to be number.

**Comment by bambooom** [comment]
@codyb1ue 应该主要就是你的表的数据类型不对，所以数据插入没有失败了，就导致了前面的错误。可以先把 `个人评分 ` 这一栏的类型改成 number 再试试
