### ISSUE TITLE
请问怎么可以把想读同步进去？

### ISSUE THREAD

**Issue by yjcaaaaaaaa** [bambooom/douban-backup#110]
原封不动挪了大佬的这是小白能力的上限了！感谢！

**Comment by yjcaaaaaaaa** [comment]
还有就是页码可以同步不

**Comment by bambooom** [comment]
@yjcaaaaaaaa 
如果是想同步到 notion，想读部分我代码里没有处理，直接过滤掉了。因为我本人没有这个需求，所以抱歉了，建议是尽快把“想读”转化成“读过” 🤣
如果是指同步到 NeoDB，这个是有的。

同步页码是指书有多少页这个么？

**Comment by bambooom** [comment]
没有回复先关了
