### ISSUE TITLE
您好，我在同步过程中出现了问题

### ISSUE THREAD

**Issue by MororoAoi** [bambooom/douban-backup#113]
按照您的方案一步步设置，除了添加integrations那一步，notion改版成了添加connections的形式。
只挑选了阅读页面的database，页面除了添加标题，其他地方都是空白。
请问能看看是哪一步出了问题吗？
非常感谢。

**Comment by bambooom** [comment]
![Screenshot 2023-09-26 at 22 06 23](https://github.com/bambooom/douban-backup/assets/14840170/ebd7ed4a-5419-4ded-a01e-23f54fd24311)

@MororoAoi  hi，我看你这里报错是没有找到对应的 database，不知道是权限不对，还是设置不对？

**Comment by bambooom** [comment]
没有回复先关了
