### ISSUE TITLE
关于图书标题和出版社的问题

### ISSUE THREAD

**Issue by Lackel** [bambooom/douban-backup#132]
大佬您好，感谢您的项目！有两个问题想向您请教:
1. 图书同步到notion后没有书名，包括您提供的自己的notion里最近的几条项目似乎也存在这个问题。
2. 图书同步过来出版社一栏包括了很多行，除出版社外还有ISBN等，是否可以修复？

再次感谢！

**Comment by bambooom** [comment]
@Lackel 感谢反馈，我才发现书名不见了 😂 最近没关注哈哈哈哈哈哈，我尽快修复
出版社栏的问题没太看明白，能不能告诉我具体是什么条目有问题，方便我测试，多谢～

**Comment by Lackel** [comment]
出版社这一栏显示这样，不知道是哪里出问题了。
![image](https://github.com/bambooom/douban-backup/assets/39994881/f1401d78-9561-4a8a-a838-78ca01d7f351)

**Comment by bambooom** [comment]
@Lackel 嗯嗯，这是具体哪个条目？你直接贴个链接给我就行，我用它调试问题

**Comment by Lackel** [comment]
每一个同步的图书条目都存在这个问题。请问您说的链接是什么？需要什么权限吗？对notion的页面分享不太熟悉

**Comment by bambooom** [comment]
@Lackel 我的图书条目里面没有这样的例子，你给我一个你截图的例子就行

**Comment by bambooom** [comment]
@Lackel 我指的是豆瓣的条目链接，不是说 notion 的页面

**Comment by Lackel** [comment]
https://book.douban.com/subject/1029111/

**Comment by bambooom** [comment]
@Lackel 嗨，谢谢提供例子，我已经更新修复了一下，麻烦再看看是否还有问题

**Comment by Lackel** [comment]
我测试了一下已经可以了。感谢这么快的回复和bug修复！
