### ISSUE TITLE
问题请教：要注意的是每个 database 都需要添加 Integration。

### ISSUE THREAD

**Issue by guoyu666** [bambooom/douban-backup#138]
你好，请问假如我要添加豆瓣电影，图书，游戏三个database的话相当于是要创建三个Integration吗？那我在 GitHub 代码仓库中设置 NOTION_TOKEN的时候不是就有三个TOKEN了吗。。。。。。

**Comment by bambooom** [comment]
@guoyu666 不是，integration 只需要创建一个，是需要在每个 database 里把 integration 加上，也就是给它权限，同一个integration 可以在多个 database 里进行操作。抱歉回复晚了

**Comment by guoyu666** [comment]
哦，这样说我就明白了，感谢感谢，thank you!!
