### ISSUE TITLE
Github Actions 无法触发

### ISSUE THREAD

**Issue by chiperman** [bambooom/douban-backup#2]
我不需要图片和音乐的部分的信息，所以在 secrets 里面就只填写了 MOVIE 的 ID。但是现在还是没有运行 actions，请问是哪里设置问题嘛？还是说必须要填写 图书、音乐 的 DATABASE ID 都需要填写才能运行？

<img width="1239" alt="截屏2021-08-09 下午2 31 34" src="https://user-images.githubusercontent.com/34889778/128667765-a94cfbee-83ad-4957-982c-e48f27dd8d60.png">
<img width="927" alt="截屏2021-08-09 下午2 31 58" src="https://user-images.githubusercontent.com/34889778/128667771-52893a69-f3f6-41ba-b44f-0ba0ad6196ef.png">
<img width="1271" alt="截屏2021-08-09 下午2 32 07" src="https://user-images.githubusercontent.com/34889778/128667774-8175ee05-aa64-472d-8270-1efcb5d106d1.png">

**Comment by chiperman** [comment]
查看了一下 log，发现时无法找到 DATABASE ID，请问是否必须得创建一个新的 page 设置为 database，然后链接到 电影 的表格，这样才可以正常运行？
<img width="1067" alt="截屏2021-08-09 下午3 49 26" src="https://user-images.githubusercontent.com/34889778/128674721-f508e3cc-36d3-4874-90fd-b61702bb4167.png">

**Comment by chiperman** [comment]
最新进展，github actions 已经跑了，但是遇到了一个问题。
这些字段是哪里来的？我记得默认不是没有这些字段吗？
<img width="1612" alt="截屏2021-08-09 下午6 53 57" src="https://user-images.githubusercontent.com/34889778/128696186-0df1a482-8fe5-476b-8941-ab6dc8096109.png">

**Comment by bambooom** [comment]
1. Actions 没有触发可能是因为我设置的是 6 个小时才跑一次的 cronjob，所以没有立刻就跑
2. 找不到 Database 可能是因为你的 Notion Integration 没有权限，需要在页面上 invite 它
3. 前两个问题似乎都解决了，第 3 个问题是这样的，IMDb、导演 这些的确是在用油猴脚本导出的时候没有的，因为那里没法获取。我忘记提供一个 Notion 模板了，这里错误处理也没做好，抱歉呐~ 你可以在你自己的 Notion Database 上加一下这几列

**Comment by chiperman** [comment]
感谢回复，目前已经成功运行 actions，但是如果我想要删除 IMDB以及其他我不需要的列，我目前在 util.js 里面的 DB_PROPERTIES 直接注释掉了一下信息。
```
  ACTORS: '主演',
  GENRE: '类型',
  IMDB_LINK: 'IMDb 链接',
```

在 action 的 log 里面会有 ```message: 'undefined is not a property that exists.'``` 这个错误信息。请问我是否还应该某个文件删除相应字段呢？第一次使用 action 和 js 脚本，还有许多地方不懂，可能需要麻烦您解答一下。谢谢。

**Comment by bambooom** [comment]
嗯 如果不想要那几列的话，只删除那几行是不够的哈，你等我晚点有空给你一个具体的方案哈，现在需要开工了  😂

**Comment by chiperman** [comment]
没问题，我也自己在摸索一下，感谢

**Comment by bambooom** [comment]
https://github.com/bambooom/douban-backup/blob/main/sync-rss.js

我昨晚更新了一下脚本，应该可以解决某些列不存在的情况

**Comment by chiperman** [comment]
好的感谢您的时间，我后续根据您的代码变动来查看一下背后的逻辑，从而了解如何自己改动。
在 2021年8月11日 +0800 AM10:10，Bamboo ***@***.***>，写道：

**Comment by chiperman** [comment]
很抱歉，您上次更改代码后，出现了跟奇怪的报错,以下是来自您的 action 的 log 信息.
```
@notionhq/client warn: request fail {
  code: 'validation_error',
  message: 'body failed validation. Fix one: body.properties.海报.title should be defined, instead was `undefined`.
body.properties.海报.rich_text should be defined, instead was `undefined`. 
body.properties.海报.number should be defined, instead was `undefined`. 
body.properties.海报.url should be defined, instead was `undefined`. 
body.properties.海报.select should be defined, instead was `undefined`.
body.properties.海报.multi_select should be defined, instead was `undefined`. 
body.properties.海报.people should be defined, instead was `undefined`. 
body.properties.海报.email should be defined, instead was `undefined`. 
body.properties.海报.phone_number should be defined, instead was `undefined`. 
body.properties.海报.date should be defined, instead was `undefined`. 
body.properties.海报.checkbox should be defined, instead was `undefined`. 
body.properties.海报.relation should be defined, instead was `undefined`. 
body.properties.海报.files should be defined, instead was `undefined`. 
body.properties.标题.id should be defined, instead was `undefined`. 
body.properties.标题.name should be defined, instead was `undefined`. 
body.properties.标题.start should be defined, instead was `undefined`.'
}
```

**Comment by bambooom** [comment]
@chiperman 哦 谢谢，最近没注意看。。。晚上修复一下

**Comment by bambooom** [comment]
@chiperman 已经修复。notion-sdk 需要更新一下，海报的值的格式修改了一下，不会报错了，不过无法在 notion 上显示出来。

另，这个 issue 我就先关闭了，有问题可以另开~ thx~
