### ISSUE TITLE
无法同步

### ISSUE THREAD

**Issue by zhouxiongh** [bambooom/douban-backup#26]
错误日志如下
Failed to create 成瘾剂量 Dopesick(http://movie.douban.com/subject/35101436/) with error:  APIResponseError: 个人评分 is expected to be number. 打分日期 is expected to be rich_text.

Failed to create 密特罗德 生存恐惧 メトロイド ドレッド(http://www.douban.com/game/35496235/) with error:  APIResponseError: 个人评分 is expected to be number. 打分日期 is expected to be rich_text.

请问 APIResponseError 是 Notion API 返回的吗？

**Comment by bambooom** [comment]
@zhouxiongh  抱歉这几天放假都没看邮件，请问是已经解决了吗？

**Comment by zhouxiongh** [comment]
是的，已经解决了 ，是原帖中的油猴脚本导出的 csv 文件建立的 database 的数据字段的问题
