### ISSUE TITLE
schedule 不能自动触发

### ISSUE THREAD

**Issue by Berminham** [bambooom/douban-backup#30]
actions 不能够自动触发 但可以手动触发

**Comment by bambooom** [comment]
这个我不确定为啥了，你要不尝试改一下那个 schedule 的时间，比如改成 1 小时，再看看是不是能正常触发到了

**Comment by Berminham** [comment]
时间改为1小时一次后居然可以了！

**Comment by bambooom** [comment]
@Berminham  那就可能之前不确定为啥没有触发到开始吧。这个 issue 我就关闭了
