### ISSUE TITLE
脚本运行正常，但标题无法记录

### ISSUE THREAD

**Issue by Dgnic** [bambooom/douban-backup#37]
Workflow 脚本运行正常，各种数据的同步也实现了，唯独没有记录下标题。

![](https://gitee.com/dgnic/multifarious-image/raw/master/img/202203172319611.png)
![](https://gitee.com/dgnic/multifarious-image/raw/master/img/202203172320627.png)
如图所示，区别于其他油猴脚本导入的数据，红框里通过脚本同步的数据都只少了标题。

![](https://gitee.com/dgnic/multifarious-image/raw/master/img/202203172322675.png)
Notion 时间轴记录里，Integration 的更新一开始就是无标题了。

代码小白，提供的图片不清楚有没有把问题说明白，如果有更多需要的截图告知我一声让我补充即可，非常感谢。

**Comment by tinainsz** [comment]
+1 好奇怪

**Comment by bambooom** [comment]
@Dgnic  我的表格完全没问题，所以实在很费解区别是啥，你方便把你的 token 还有 databse id 的信息发给我，方便我在本地测一测？也可以把你的 database 页面 share 一下，我研究一下？不好意思麻烦了

**Comment by bambooom** [comment]
话说为啥你的 notion 截图是中文的，我在 settings 里面选择语言没有中文的选项

**Comment by Dgnic** [comment]
可以的，Github 似乎没有站内私信功能，你方便留个邮箱吗？

关于 Notion 的中文，现在只能用第三方的油猴插件进行汉化，真正的本地化还没有实现。具体可以看：https://github.com/Reamd7/notion-zh_CN

**Comment by bambooom** [comment]
@Dgnic  nmz89825 at gmail.com 
at 换成 @

**Comment by Dgnic** [comment]
好的，已经发送了

**Comment by tinainsz** [comment]
> +1 好奇怪

update一下，今天发现电影莫名奇妙正常了（可以写入标题）但豆瓣图书依然不行，不知道是不是某种间歇性问题……

**Comment by bambooom** [comment]
哈 谢谢 update，我本地研究过，应该真的不是我的问题，我觉得是 notion sdk 的问题，已经给他们发了 support 邮件以及 issue，但是不知道什么时候才会有回复或者修复了

**Comment by yslemmo** [comment]
好奇怪，我也遇到这样的问题。都无法显示标题

**Comment by bambooom** [comment]
之前发的 issue 没人理我，发的 support 邮件之前只是一个类似客服的人说已经通知 SDK team 的人去查，不过不知道时间，也没有下文。。。摊手

**Comment by Dgnic** [comment]
试试点击 Notion 右下角那个问号直接给他们发消息呢...

**Comment by bambooom** [comment]
@Dgnic  那个和发邮件的效果差不多的，我之前另外发现个 bug 试过

**Comment by YuanZhou314** [comment]
+1 ，找了一下午没看出来啥问题，最后我新建了一个数据表格，就可以正常填标题了，但是评分又消失了……鉴于评分可以直接选择我就懒得管了，能用就行。

**Comment by hushhw** [comment]
坚持手动填标题很久了，有解决方案了踢我一下

**Comment by bambooom** [comment]
竟然差不多一年了还有人有问题，我晚点再重新 debug 看看

**Comment by TheWanderingAllison** [comment]
发现原来这么多人都碰到这个问题……我之前一直是没有问题的，直到最近因为想同步neodb所以sync了一下作者的原始仓库（此前是2022年初fork了一次后续就没再sync过），就是这次sync后虽然neod能同步但是同步到notion的全都缺了标题

**Comment by bambooom** [comment]
主要我自己的 notion 从来没有过这个问题。。。几乎无法 debug，所以这个 issue 一直没有 close

**Comment by edwardcuchulainn** [comment]
我之前也没有问题，这两周开始没有标题了……

**Comment by JOKER120YL** [comment]
用的两年的仓库一直没问题。最近想起来同步到最新的仓库了，发现也是这个问题，标题无法记录

**Comment by JOKER120YL** [comment]
update：我重新翻找了下你的最新教程（ps：GitHub上这个教程链接失效了），然后根据里面的模板，将我notion界面的标题栏目重命名成和你一样的“电影/电视剧/番组”然后好像就能捕捉标题了。我如果后期没继续更新可能问题就解决了。其他人或许可以参考下我的解决方式

**Comment by bambooom** [comment]
> 还是想自定义自己的notion标题的可以接着看下去。

👌 收到

各位实在抱歉，太久没维护这个工具，最近生活里还有点事在忙，最快下个月会来更新！

**Comment by bambooom** [comment]
又过了两个月终于来搞这个了。。。
我这边加了个 [`cols.json`](https://github.com/bambooom/douban-backup/blob/main/cols.json) 文件。
有需要的话修改这个文件里的配置，把对应的 column name 改成你想用的名字就行了哈。

如果还有问题的话，麻烦再回复告知。
