### ISSUE TITLE
脚本运行失败

### ISSUE THREAD

**Issue by huhexian** [bambooom/douban-backup#41]
这是我的仓库地址：https://github.com/huhexian/douban-backup
![image](https://user-images.githubusercontent.com/42113492/162560604-9d73b6b9-89d3-4e01-bd41-642880a9b2ec.png)
![image](https://user-images.githubusercontent.com/42113492/162560623-55c94c14-c75b-45e9-9cfc-25704ff90dd5.png)
Error: Process completed with exit code 1.
我不太懂这些，按照教程设置好之后，运行失败，不知道咋解决😥

**Comment by bambooom** [comment]
@huhexian  

![Screen Shot 2022-04-10 at 10 37 23 PM](https://user-images.githubusercontent.com/14840170/162624620-a959e40f-a5b0-4872-9507-07984eb7e525.png)

看这里的错误消息是说你的 notion database id 大概填错了，你可以截个图看下 书的 id 这个是怎么填的么？

**Comment by huhexian** [comment]
> 

但是我没有填book的，只填了movie的

**Comment by huhexian** [comment]
> @huhexian
> 
> ![Screen Shot 2022-04-10 at 10 37 23 PM](https://user-images.githubusercontent.com/14840170/162624620-a959e40f-a5b0-4872-9507-07984eb7e525.png)
> 
> 看这里的错误消息是说你的 notion database id 大概填错了，你可以截个图看下 书的 id 这个是怎么填的么？


但是我没有填book的，只填了movie的

**Comment by bambooom** [comment]
👌 那我知道了，原来我自己记错了，我稍微修一下 bug

**Comment by bambooom** [comment]
@huhexian  我更新了，麻烦同步一下你的仓库，应该可以了

**Comment by huhexian** [comment]
> @huhexian 我更新了，麻烦同步一下你的仓库，应该可以了

好的，我试试

**Comment by huhexian** [comment]
> @huhexian 我更新了，麻烦同步一下你的仓库，应该可以了

成功了，谢谢！！！

**Comment by bambooom** [comment]
👌   issue 我就 close 了
