### ISSUE TITLE
网站上的油猴脚本怎么把海报也弄下来啊？

### ISSUE THREAD

**Issue by elizen** [bambooom/douban-backup#45]
按照网站的教程，完美的弄完了书和影视，通过 Github Action 同步的内容都可以顺利搞定。

但是之前我还有 700+ 的电影，没有海报...请问有什么办法可以把它们弄下来么，合并到 Notion 中么？

**Comment by bambooom** [comment]
油猴脚本爬的数据有限制，就是没有海报的，暂时没有什么办法解决

**Comment by elizen** [comment]
> 

好的，感谢。那就每天搞十张八张的，哈哈哈。小步快跑吧。

**Comment by elizen** [comment]
> 

好的，感谢。那就每天搞十张八张的，哈哈哈。小步快跑吧。

**Comment by bambooom** [comment]
不好意思，谢谢理解🙏
