### ISSUE TITLE
豆瓣新增了记录，RSS 地址内也有更新，但一直 0 new item

### ISSUE THREAD

**Issue by nanvon** [bambooom/douban-backup#59]
我的豆瓣 RSS 地址为 https://www.douban.com/feed/people/nanvon/interests ，今天 8 月 31 日，可以看到我新增了两条测试记录（书籍、电影），但是依旧提示 0 new item。https://github.com/nanvon/douban-backup/actions
![image](https://user-images.githubusercontent.com/36064282/187629290-9b1e0d81-e2cb-4fc7-b1f5-4c29919c20a3.png)

**Comment by nanvon** [comment]
我在本地测试运行，发现没问题，不知道为什么在 GitHub Actions 上检测不到 new items 。
![image](https://user-images.githubusercontent.com/36064282/187640224-cacc2e2c-ab09-469f-8b50-2f0fefc6afb8.png)

**Comment by nanvon** [comment]
我将仓库删掉，重新 fork ，但依旧有这个问题：GitHub Actions 上 0 item ；在本地运行没问题。

**Comment by bambooom** [comment]
抱歉才看到，我自己这边似乎也有类似问题，等我仔细看看

**Comment by nanvon** [comment]
> 抱歉才看到，我自己这边似乎也有类似问题，等我仔细看看

我今天又捋了一遍代码，发现问题可能在 [sync-rss.js#L138-L151](https://github.com/bambooom/douban-backup/blob/main/sync-rss.js#L138-L151)，我看到 7 月 26 日您修改了这处代码，我尝试回退该 commit，再次分别在 GitHub Action 和本地运行代码，都没有问题，可以正常添加了。

**Comment by bambooom** [comment]
@nanvon 确实，不知道为啥上次有问题我才改的，已经 revert 掉了，谢谢！抱歉拖了这么久。。。
