### ISSUE TITLE
出版日期格式不一样导入失败

### ISSUE THREAD

**Issue by leewint** [bambooom/douban-backup#64]
https://book.douban.com/subject/1578545/ 读完这本书的时候，发现导入不了，脚本报错。
![image](https://user-images.githubusercontent.com/44335558/193277107-bfd60ae3-31d9-4d75-9bf0-b961182460af.png)
然后导入其他书籍就可以正常导入，然后发现《背叛》这本书的出版年是：2000年5月，其他的书的出版年是：2013-6-1，所以就是出版年不一样导致不兼容，导致脚本报错，导入不了。

**Comment by bambooom** [comment]
@leewint  嗯，确实是这个格式我没见过没考虑过，已经修了一下，可以再试试

**Comment by leewint** [comment]
这个问题解决了，我测试了一下，发现现在的代码会将正常的日期格式去掉最后一个字符，比如：“2022-3-23”导入后就变成“2022-3-2”了，应该是一个bug。

**Comment by bambooom** [comment]
@leewint  啊是呢，顾此失彼了。。。刚刚改掉了

**Comment by leewint** [comment]
好了，抱拳！
