### ISSUE TITLE
scheduled workflow 最后一次run是在25天之前

### ISSUE THREAD

**Issue by wyih** [bambooom/douban-backup#7]
Hi, 我又来了, 我今天发现我之前设好的两个douban账号都停在了25天之前. 查看Action发现25天最后一次run之后就没有run过. 我中间没有动过设置, 不知道是不是因为是schedule workflow, 我在action里也找不到可以manually run的地方? 只好disable再enable了看看能不能恢复. 想问一下这是因为什么原因造成的,以及如何修复...

**Comment by wyih** [comment]
表达能力差到这个地步的了, 这上面写的中文怎么看都像是机翻出来的...

**Comment by bambooom** [comment]
@wyih  嗯对，RSS 只有最近 10 条的，所以太早的肯定不在里面了，可能得手动整理一下了，不好意思哈
