### ISSUE TITLE
豆瓣增加记录后同步错误

### ISSUE THREAD

**Issue by ethanjtch** [bambooom/douban-backup#82]
我刚按照博客教程设置好整个流程，在没有增加记录的情况下run workflow成功。

之后我就增加了一本图书阅读记录，再手动run workflow就显示有问题。

https://github.com/ethanjtch/Douban2Notion/actions/runs/5108313507/jobs/9182008048
<img width="1111" alt="SCR-20230529-kypv" src="https://github.com/bambooom/douban-backup/assets/19629402/1eea0c93-fea6-4e7a-af47-2f248daf4154">

**Comment by bambooom** [comment]
不好意思回复晚了，我看新的自动跑的 job 没有报错，请问是已经解决了？

**Comment by bambooom** [comment]
不过仔细看了一眼，你的这个 database id `f8ec50c0-ffd5-4bdf-84f1-616134390fa2` 设置得不太对，正常的 id 是不包含连接符号 `-` 的，或者你可以修正一下你的 database id 的设置，去掉 `-`，重新跑一下看看

**Comment by ethanjtch** [comment]
那问题应该就在这里，我很确定填写的时候是没有 - 的。

Ethan

在 2023年5月30日，11:01，Bamboo ***@***.***> 写道：

﻿

不过仔细看了一眼，你的这个 database id f8ec50c0-ffd5-4bdf-84f1-616134390fa2 设置得不太对，正常的 id 是不包含连接符号 - 的，或者你可以修正一下你的 database id 的设置，去掉 -，重新跑一下看看

**Comment by ethanjtch** [comment]
补充：我刚才在豆瓣增加了一个已读，然后手动run workflow，就又出问题了。😭

Ethan

在 2023年5月30日，11:21，Chen Ethan ***@***.***> 写道：

﻿那问题应该就在这里，我很确定填写的时候是没有 - 的。

Ethan

在 2023年5月30日，11:01，Bamboo ***@***.***> 写道：

﻿

不过仔细看了一眼，你的这个 database id f8ec50c0-ffd5-4bdf-84f1-616134390fa2 设置得不太对，正常的 id 是不包含连接符号 - 的，或者你可以修正一下你的 database id 的设置，去掉 -，重新跑一下看看

**Comment by bambooom** [comment]
这。。有点不能理解了，你方便分享给我你的这个 id 的页面吗？我晚点试试？

**Comment by bambooom** [comment]
啊 不过如果填写没问题，这里可能只是错误信息的显示方法不一样，你有给这个 database 页面添加权限吗？

**Comment by ethanjtch** [comment]
我把这一页publish了，你看下是否可以？

<https://ethan-mind.notion.site/f8ec50c0ffd54bdf84f1616134390fa2?v=9e84fd9bbe234737b0f502d3dde625d5>
book template<https://ethan-mind.notion.site/f8ec50c0ffd54bdf84f1616134390fa2?v=9e84fd9bbe234737b0f502d3dde625d5>
ethan-mind.notion.site<https://ethan-mind.notion.site/f8ec50c0ffd54bdf84f1616134390fa2?v=9e84fd9bbe234737b0f502d3dde625d5>
[X]<https://ethan-mind.notion.site/f8ec50c0ffd54bdf84f1616134390fa2?v=9e84fd9bbe234737b0f502d3dde625d5>


2023年5月30日 12:10，Bamboo ***@***.***> 写道：



这。。有点不能理解了，你方便分享给我你的这个 id 的页面吗？我晚点试试？

**Comment by ethanjtch** [comment]
确定给了权限的。

[SCR-20230531-kppf.png]


2023年5月30日 12:12，Bamboo ***@***.***> 写道：



啊 不过如果填写没问题，这里可能只是错误信息的显示方法不一样，你有给这个 database 页面添加权限吗？

**Comment by bambooom** [comment]
额 我看了眼最新自动跑的这个job成功了呢，而且添加了新的书的记录， https://github.com/ethanjtch/Douban2Notion/actions/runs/5129539638

你要不再试下手动还有没有问题？

**Comment by ethanjtch** [comment]
哇哦，是有那么点神奇在的，怀疑是manually run有问题……

我刚在每个类目里都加了一条新的豆瓣记录，调整了1小时后生效，看下结果。

Ethan

发件人: Bamboo ***@***.***>
日期: 星期三, 2023年5月31日 16:04
收件人: bambooom/douban-backup ***@***.***>
抄送: Ethan Chen ***@***.***>, Author ***@***.***>
主题: Re: [bambooom/douban-backup] 豆瓣增加记录后同步错误 (Issue #82)

额 我看了眼最新自动跑的这个job成功了呢，而且添加了新的书的记录， https://github.com/ethanjtch/Douban2Notion/actions/runs/5129539638

你要不再试下手动还有没有问题？

―

**Comment by ethanjtch** [comment]
Update: 一切运行正常

非常感谢！

Ethan

2023年5月31日 16:14，Chen Ethan ***@***.***> 写道：

哇哦，是有那么点神奇在的，怀疑是manually run有问题……

我刚在每个类目里都加了一条新的豆瓣记录，调整了1小时后生效，看下结果。

Ethan

发件人: Bamboo ***@***.******@***.***>>
日期: 星期三, 2023年5月31日 16:04
收件人: bambooom/douban-backup ***@***.******@***.***>>
抄送: Ethan Chen ***@***.******@***.***>>, Author ***@***.******@***.***>>
主题: Re: [bambooom/douban-backup] 豆瓣增加记录后同步错误 (Issue #82)

额 我看了眼最新自动跑的这个job成功了呢，而且添加了新的书的记录， https://github.com/ethanjtch/Douban2Notion/actions/runs/5129539638

你要不再试下手动还有没有问题？

―

**Comment by bambooom** [comment]
诶，看来前两天是 notion API 自己不稳定吧，我这边啥也没动，现在一切正常就好！
我先 close 了～
