### ISSUE TITLE
脚本正常运行，但标记无法同步

### ISSUE THREAD

**Issue by Yuu11983** [bambooom/douban-backup#90]
![image](https://github.com/bambooom/douban-backup/assets/102215540/10eb1d84-1ec6-48ae-8d64-f1baeee900f1)
除了偶尔一次运行失败以外，脚本都是正常运行，notion页面也已经连好了Bot，请问是哪里出了问题呢
![image](https://github.com/bambooom/douban-backup/assets/102215540/20344094-ff97-4b59-b879-a7e32fa68663)

**Comment by bambooom** [comment]
![Screenshot 2023-06-08 at 16 20 36](https://github.com/bambooom/douban-backup/assets/14840170/a58a9869-aa4e-4b1e-ac50-e49f8979f2f3)

看了一下，里面其实有报错，应该是“条目链接”这一列的数据类型选择不对，应该是 URL，不是 text

**Comment by bambooom** [comment]
我会再改一下报错部分，让错误明显一点

**Comment by bambooom** [comment]
hello，我已经更新了一下脚本，可以再手动跑一下，报错会更明显一点

**Comment by Yuu11983** [comment]
`感谢回复！！因为是小白不懂怎么用github所以找不到报错的地方，修改过后已经可以运行了。
可能因为我是直接导入的csv，没有用你创建好的模板，所以会出现这样的问题。感谢！！
不过在改的时候发现一个小小的问题，你的template里海报type是files&media，我一开始是设置成了url，但报错并显示‘海报is expeted to be url‘，然后我就疑惑地卡在这里了。不过观察你的template发现海报的类型其实是files&media，改成这个类型就成功了~~
