### ISSUE TITLE
书籍的出版社老是读不出来

### ISSUE THREAD

**Issue by jnfutouge** [bambooom/douban-backup#93]
挺好用的。
小bug，豆瓣书籍的出版社总为空。

**Comment by bambooom** [comment]
@jnfutouge 

可以分享一下具体的条目，还有你的 notion 页面嘛？
我自己这里一直都没问题

**Comment by bambooom** [comment]
@jnfutouge 

啊 我发现问题在哪里了，已经修了，麻烦再试试确认一下

**Comment by jnfutouge** [comment]
确实是好了，大佬牛逼

**Comment by bambooom** [comment]
没问题就好 👌
